### ISSUE TITLE
Backup fails if some files/folders are not readable

### ISSUE THREAD

**Issue by asmerovski** [spersson/Kup#22]
If some files or folders that were under backup are deleted, error pops up in notification area and backup is stopped.
Error message:
Indexing of file system did not complete successfully: reduce_paths: [Errno 2] No such file or directory: '/home/asmer/VirtualBox VMs' reduce_paths: [Errno 2] No such file or directory: '/home/asmer/Edraw Max' reduce_paths: [Errno 2] No such file or directory: '/home/asmer/vmware' WARNING: 3 errors encountered.

How to reproduce:
1. Set versioned backup of home folder.
2. Run backup.
3. When backup is completed, delete some folders.
4. Run backup again.

Environment info:
Kubuntu 14.04.1 LTS 64-bit
Kup version 0.4.0-1

**Comment by spersson** [comment]
I am closing this issue since I have now made a solution (not perfect, but at least it's something) that warns the user while creating a backup plan... when selecting what to include in backup a warning is displayed if there is any file or folder included that can not be read by the user.
If unreadable file is added after backup plan was created there is still nothing and the backup will fail, same as before.
