### ISSUE TITLE
rsync type of backup adds parent folder structure

### ISSUE THREAD

**Issue by HinzundKunz** [spersson/Kup#29]
I want to do a rsync from /home/martin/Documents/folder1/folder2 to a samba share mounted on /media/martin/folder3. Folder 2 and folder 3 should have the same content afterwards.

What kup does is: create /home/martin/Documents/folder1/folder2 in /media/martin/folder3 and syncs in there..

**Comment by spersson** [comment]
Yes, this is intentional. My thinking was that if you are backing up two folders with the same name (/home/user1/docs and /home/user2/docs for example) then you get a name conflict. This can be solved by finding closest common parent folder and placing the backups within a folder with that name. But then you need to handle the case where only one of the folders was backed up first, the second folder added later..causing a change of root folder.  Would need to detect that and move stuff on the destination side on the first run after the "root" folder has changed. This whole situation is perhaps an unlikely problem but I think a backup program should handle all situations correctly. So the complexity would have to be handled. I did not want to do that based on the assumption that a user would not mind spending 5 seconds extra to navigate to his files in case his hard drive died. (Basically assuming that backups will be accessed very rarely).
Leaving this issue open as a feature suggestion for now, to give some time for more thoughts and discussion.

**Comment by adrfantini** [comment]
I think that a simple config option to set/unset this behaviour would be a nice feature.

**Comment by Silicomancer** [comment]
I support this suggestion.

**Comment by spersson** [comment]
Why would you want it?
Is my assumption wrong? (that the user will only look at the backup in the rare case of actual data loss...)
Speaking just for myself, during my last couple of years of taking regular backups I have _never_ looked at backed up data since I never actually had a data loss.

Anyway, as always I am very grateful for feedback and suggestions! Keep it coming! :)

**Comment by adrfantini** [comment]
Yes, your assumption is wrong.

Example 1: I have data on my desktop computer which I refularly backup on a 2.5" HDD. When I move around, I of course bring the HDD with me, and I use that, so I want the directory structure to be the same.

Example 2: I have data connected to my router via USB. I upload to that via WiFi from my laptop every time I change something. I daily backup that data to my desktop, which I use also daily to watch movies etc. Yes, I could watch them in streaming from my router, but what' the point when I have a local copy of the data available?

**Comment by Silicomancer** [comment]
Similar here. One of my backups also is a productive copy on a Laptop.

**Comment by ciacnorris** [comment]
I'm joining this conversation upon your invitation on KDEApps.

My thoughts:
- this choice should be presented as a radio button selection in the Destination tab. There should be three options*;
- the default behaviour should be #1*;
- a preview of the resulting path of the backup should be shown under this radio button selection area.

* to stick with the first example, let's say /home/martin/Documents/folder1/folder2/content are all the files and subfolders one wants to backup. The three options could be:
1. /media/martin/folder3/content [default]
2. /media/martin/folder3/folder2/content
3. /media/martin/folder3/home/martin/Documents/folder1/folder2/content [actual behaviour]

OT thoughts:
- the show hidden folders option should be presented in the Sources tab, not in the Advanced tab, where it's too late in the workflow;
- because of the (probably stupid) way I manage my files, I would find very useful being able to unselect just some files in a folder. Showing all the files in the Source tab by default could make things more confusing, but a “Show files” checkbox could be added;
- maybe “incremental backup“ and “synchronised backup” should be switched (and the latter should be made the default choice), because the user that doesn't understand the difference (or doesn't want to take time to understand) usually doesn't want to end up with a backup he can't browse with his file manager;
- it would be great to have a way to see the progress status of the backup - in terms of percentage, files currently being copied and/or files already copied -, from a tooltip appearing when hovering on the tray icon and/or from the main window;
- some reference should be added to get software name, version, authors and where to report bugs. While using Kup, some automatic tool brought me to the KDE bugtracking system suggesting to report a bug/feature request for kcm, and I filed a bug here just to be said that wasn't the right place :)

Anyway, thanks a lot for this great piece of software!
