### ISSUE TITLE
External storage media not showing up in backup destination

### ISSUE THREAD

**Issue by Neudrino** [spersson/Kup#31]
**Problem:**
Some of my external media are not showing up under the "choose external (USB-)media as backup destination".

**More Details:**
I have two external USB Devices: 1x USB flash drive, 1x USB HDD.
Both are USB3 and connected to USB3 Ports. Both work fine with the Kubuntu system, e.g., they work normal with Dolphin. Now on the Flash Drive there are 2 partitions, while on the HDD there is only 1. When I connect both devices, the partitions of the flash drive are available as backup destination, while the HDD is not.

**Expected behaviour:**
All USB Media should show up in the selection screen for backup destination.

**Further Suggestions:**
Can you upgrade, that all available media on the machine show up? One might have multiple internal drives (partitions) and want to backup from one to another, as soon as it is mounted.

**System:**
Kubuntu 14.04
KDE SC 4.13.2
Linux 3.13.0-55-generic
kup_0.5.1-1_amd64 (of 2015-06-29)
Flash drive: 170c:5106 ASMedia
USB-HDD: 13fe:5000 Kingston

I enclosed a screenshot that you get an idea. If you need further output, let me know how to obtain it.
![kub-bug-ext_hdd_not_showing_up](https://cloud.githubusercontent.com/assets/13189449/8513163/31e8c506-2360-11e5-816a-3cbb606500b8.jpg)

**Comment by spersson** [comment]
Is there something special about the hard drive? You are saying that it does not show up at the same time as the flash drive, but does it work when only the hard drive is connected? Can you also try to see if it makes a difference if the drive is already plugged in when starting system settings, compared to plugging in the drive after opening the backup settings?
Thanks!

**Comment by Neudrino** [comment]
Thanks for your reply! To put it short:
It is working now!

I do not really know what the problem was / is. There are several things, which were strange and hard to reproduce. Anyway restarting the PC and connecting the device in question before starting the Kup configuration dialogue was leading to the expected result.

> You are saying that it does not show up at the same time as the flash drive, but does it work when only the hard drive is connected?
Can you also try to see if it makes a difference if the drive is already plugged in when starting system settings, compared to plugging in the drive after opening the backup settings?

There are still some other issues with my current backup plan. But if the backup works, I will check upon the different connection states and procedures of the device again. I am also going to set up Kup on a second computer, as soon as I got the first copy working. I can also check with both Backup destinations when I do this.
But this might be delayed some time, as I am very busy the next months...

**Comment by Neudrino** [comment]
Sorry, did not want to close the issue, as I am not the developer. Just got the wrong button...

**Comment by Filibilli** [comment]
Hi there,
I'm also having the same problem.
Kubuntu 15.04, Plasma 5
kup_0.6.0-2_amd64 (from the GitHub Launchpad address).
I have a WD Mybook which the KDE system sees OK and can use. This doesn't get seen by Kup. If I add a USB-stick then it gets recognized.

![kup_no mybook](https://cloud.githubusercontent.com/assets/13314163/8649167/bced2cfc-2967-11e5-9576-6eb5640e4d3a.png)

I've tried restarting the PC with and without the MyBook connected but unfortunately all to no avail.

Any ideas would be appreciated.

Best regards
Phil

**Comment by t2000** [comment]
I have exactly the same problem as Filibilli on Gentoo with newest plasma stuff and kup 0.6.0.tgz. My 2TB ext4 formated HDD is not recognized by kup but by plasma (dolphin) and I can mount it there.

My exfat formated SD card is displayed in kup, I dont know why the HDD is not.

However if I attach this HDD to an older laptop running kubuntu 14.4 with an older version of kup on kde4 and there it works (kup shows the HDD).

**Comment by spersson** [comment]
Hello dear users!
First, I am sorry for the late reply.. life keeps me busy. If any of you would be willing to help me find out why your harddrives are not showing up, I would appreciate some help! I don't own a device with this issue so I'm very much stuck without some help.
Ok, so... these are the commands to run from a terminal in order to see the available storage volumes on your system, using the same selection criteria as Kup currently uses:

```
solid-hardware5 query "StorageDrive.hotpluggable == true"
```
That should list your external harddrives currently plugged in and perhaps a CD-drive if you have one. If you can't see the harddrive listed then we have already found the problem.... Next, copy the udi string shown for your harddrive, then enter this command with the copied udi string pasted as the last argument:
```
solid-hardware5 query "[ StorageVolume.ignored == false AND [ StorageVolume.usage == 'FileSystem' OR StorageVolume.usage == 'Encrypted' ]]" '/org/freedesktop/UDisks2/drives/WDC_WD50_00BPVT_22HXZT3_FDC0FD500000000FD0FF41E72F5645'
```

(This example show the udi for my external western digital drive).

Normally your harddrive's partition should be listed by this command but since it is not working for you, it probably will NOT be shown then...
If you can't see it being listed (it should show something like udi = '/org/freedesktop/UDisks2/block_devices/sdb1') then please try modifying the query until it is listed... Try removing the "ignored" condition for example:
```
"[ StorageVolume.usage == 'FileSystem' OR StorageVolume.usage == 'Encrypted' ]" 
```

Then please let me know your findings!
Thanks a lot for reporting!

**Comment by Filibilli** [comment]
Hi,

just tried this and the first command revealed that 
libkf5solid-bin
was not installed. I corrected this (maybe the problem) and get:
fil@fil-desktop:~$ solid-hardware5 query "StorageDrive.hotpluggable == true"
udi = '/org/freedesktop/UDisks2/drives/USB_Mass_Storage_Device_816820130806'
udi = '/org/freedesktop/UDisks2/drives/WD_My_Book_1170_574D43315434303036393433'

The disk I use is the second entry.

I just called up the option in the kde settings and lo and behold: kup has seen my disk and asked me if I want to perform a backup :-)

Seems like it was that simple.

Thanks for your help and for the great software!

Cheers

Fil

**Comment by t2000** [comment]
Unfortunately this does not work for me. I do have the command "solid-hardware5" installed. and "solid-hardware5 query "StorageDrive.hotpluggable == true"" returns nothing :(

However a "solid-hardware5 --list" shows the harddrive as:
udi = '/org/freedesktop/UDisks2/drives/ST2000LM003_HN_M201RAD_S362J9FGA70138'

And a "solid-hardware5 details /org/freedesktop/UDisks2/drives/ST2000LM003_HN_M201RAD_S362J9FGA70138"

produces:

udi = '/org/freedesktop/UDisks2/drives/ST2000LM003_HN_M201RAD_S362J9FGA70138'
  parent = '/org/freedesktop/UDisks2'  (string)
  vendor = ''  (string)
  product = 'ST2000LM003 HN-M201RAD'  (string)
  description = 'ST2000LM003 HN-M201RAD'  (string)
  Block.major = 8  (0x8)  (int)
  Block.minor = 17  (0x11)  (int)
  Block.device = '/dev/sdb1'  (string)
  StorageDrive.bus = 'Sata'  (0x4)  (enum)
  StorageDrive.driveType = 'HardDisk'  (0x0)  (enum)
  StorageDrive.removable = true  (bool)
  StorageDrive.hotpluggable = false  (bool)
  StorageDrive.inUse = true  (bool)
  StorageDrive.size = 2000398933504  (0x1d1c1115e00)  (qulonglong)

Which means my hard drive is recognized as removeable but NOT hotpluggable for some reason... So what is the difference for solid?

Hope you can explain and fix it by also listening the removeable device that are not hotpluggable.

Thanks for your great work, though!

**Comment by spersson** [comment]
Yeah, perhaps only hiding drives which are neither removable nor hotpluggable would be a good solution! I never took the time to fully understand the difference of those two.
Your hard drive is connected with eSata cable, not USB? Just curious because that case has been reported before and my conclusion then was that there is no way to tell the difference between an external eSata drive and an internal Sata.
If that is the case then it makes sense to me, you need to have an eSata drive plugged in at boot in order to see it, if I understand it correctly. So it's not hotpluggable. But it is removable. It was just that I thought that in this case there was no way for the system to detect that it is removable....

**Comment by t2000** [comment]
No, my external Harddrive is a USB drive, USB 3.0 though. Maybe it has an internal USB-to-SATA controller which is why it shows up as such.

But I just looked at my internal SSD which is connected via SATA and there it shows:

solid-hardware5 details /org/freedesktop/UDisks2/drives/TOSHIBA_THNSNJ512GCSU_85ES10KMT8PW

udi = '/org/freedesktop/UDisks2/drives/TOSHIBA_THNSNJ512GCSU_85ES10KMT8PW'
  parent = '/org/freedesktop/UDisks2'  (string)
  vendor = ''  (string)
  product = 'TOSHIBA THNSNJ512GCSU'  (string)
  description = '476,9 GiB Hard Drive'  (string)
  Block.major = 8  (0x8)  (int)
  Block.minor = 5  (0x5)  (int)
  Block.device = '/dev/sda5'  (string)
  StorageDrive.bus = 'Sata'  (0x4)  (enum)
  StorageDrive.driveType = 'HardDisk'  (0x0)  (enum)
  StorageDrive.removable = false  (bool)
  StorageDrive.hotpluggable = false  (bool)
  StorageDrive.inUse = false  (bool)
  StorageDrive.size = 512110190592  (0x773c256000)  (qulonglong)


So this is neither removable not hotpluggable. Thus, my aforementioned solution should work, if I am not completely mistaken.

**Comment by spersson** [comment]
I made the change to show drives if they are removable or hotpluggable, in commit 3616176ce6335e8e4115a6c1a791838e3b5e0370. I will assume that fixes it and close this issue. Thanks to all you guys for reporting and helping to figure out what was going on... (I guess there can be more issues causing drives not to show up, but at least one cause fixed is enough for me to close this for now... :)
