### ISSUE TITLE
Rsync - Copy files and folders linked from source folder

### ISSUE THREAD

**Issue by LeandroCardoso** [spersson/Kup#38]
I am using kup-rsync to copy some directories that are actually links to directories not included in the list of directories to be backed up. So, the directory link is copied, it points to an invalid place, and the content of the directory were not backed up. I expected that the files inside the directory link to be copied.
Maybe, a better behaviour is to use the --copy-links and --copy-dirlinks parameters. We will lose the link semantic, but I believe this is much better than to not copy the directory content.

**Comment by spersson** [comment]
On Wednesday, 6 January 2016 18:40:20 SGT Leandro wrote:
> I am using kup-rsync to copy some directories that are actually links to
> directories not included in the list of directories to be backed up So, the
> directory link is copied, it points to an invalid place, and the content of
> the directory were not backed up I expected that the files inside the
> directory link to be copied Maybe, a better behaviour is to use the
> --copy-links and --copy-dirlinks parameters We will lose the link semantic,
> but I believe this is much better than to not copy the directory content
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spersson/Kup/issues/38

Thanks for the suggestion!
As a starting point a backup program should create an exact copy of what the user wants a 
backup of, I think everybody will agree on that... But of course I do see the risk of 
misunderstanding or forgetting in this case that you bring up. And believing that you have a 
complete backup when in fact you have a bunch of useless links would be, eh... not good. 
So yes, copying files that was not requested to be backed up is perhaps a good in the case 
that there is reason to believe that the only reason for their omission is that the user has been 
forgetful or misled. 
The fact that a user has created a link among her important files would indicate that the files 
being pointed to are also likely to be important to the user.

But if Kup is changed to do what you suggest, then what about people who do the right thing 
of including the folders that actually contain the files? They would be punished for doing the 
right thing by needlessly getting two copies of all those files on the backup, would they not?
Can rsync be convinced to only replace a symlink with a directory if the directory being 
pointed to does not exist and will not exist after rsync completes the current run? (that last 
condition is for covering the case of first run backup, perhaps the directory has not been 
copied already when rsync encounters the symlink...)

I would very much like to avoid having to make Kup scan the filesystem in order to detect 
situations like this. Much nicer when filescanning is only done by the program doing the 
copying (bup, rsync).

**Comment by spersson** [comment]
I decided to resolv this in a different way... Now the configuration module just detects problem symlinks (pointing to stuff not currently included in backup plan) and warns the user about it. I think that is a reasonable solution. Still possible to get it wrong, for example by adding the symlink after having configured the backup plan... then you will not get any warning unless you open the backup plan configuration for some reason.
So... not a perfect solution, but a reasonable compromise, I think.
