### ISSUE TITLE
Not possible to exclude sub folders that can not be read

### ISSUE THREAD

**Issue by sbaragnaus2** [spersson/Kup#39]
Hi,
I've tried to backup my pictures drive (ext4 filesystem) to an external hd (ext4 filesystem).

I can't complete my backup due to a denied permission in the "lost+found" folder. 

How can I exclude that directory? It's grayed out in backup configuration. I'm using kup 0.6 and Kde 5.5.3. 

Here is the log:

------------start-------------

Kup is starting rsync backup job [...]
rsync -aR --delete --delete-excluded --exclude=/home/sbaragnaus/pictures/Downloads /run/media/sbaragnaus/Verbatim/backup-kup
rsync: opendir "/home/sbaragnaus/pictures/lost+found" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

Kup did not successfully complete the rsync backup job.

---------end------------------

Thanks

**Comment by sbaragnaus2** [comment]
Any support, please? Is this project dead? Thanks

**Comment by spersson** [comment]
Not dead, no. Just a one-man show still. And I've been busy for the last year.
Thanks for reporting! I think you have found an issue I never thought about. The folder item is greyed out because the folder can not be read, so you should not be able to select it. But I never thought about the situation where it is inside of a backed up folder and you need to exclude it. Perhaps it should still be greyed out, but automatically deselected (excluded)?
That seems like a small nice fix if somebody wants to help this project. Otherwise I will have a look at it when I have time and energy.
Thanks again!

**Comment by sbaragnaus2** [comment]
> Perhaps  it should still be greyed out, but automatically deselected (excluded)?

Yes, this should be a solution.

I hope you (or any contributor) will fix it soon.

Thanks

**Comment by spersson** [comment]
I decided to resolv this in a different way... Now the configuration module just detects problems with files and folders that cannot be read and warns the user about it. I think that is a reasonable solution. Still possible to get it wrong, for example by adding unreadable files or folders after having configured the backup plan... then you will not get any warning unless you open the backup plan configuration for some reason. But taking a new backup will fail and that probably makes you open the configuration...
So... not a perfect solution, but a reasonable compromise, I think.
