### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by lboullo0** [spersson/Kup#41]
Hello, I'm evaluating to start using Kup but I've seen little activity in it. I wonder if it's safe to use to backup my files in Kubuntu 16.04.

https://www.openhub.net/p/kup

**Comment by spersson** [comment]
It's as safe to use for backups as it ever was. Since kup is basially just a scheduler, most of the safety aspect comes from the programs used for actually copying the data, rsync and bup. Both of those are actively maintained. One reason that activity on kup has slowed down is basically that it is "good enough" for my own and many other's needs.
