### ISSUE TITLE
Require ac power / full battery or pause power management for doing backups

### ISSUE THREAD

**Issue by m0uH** [spersson/Kup#47]
While doing backups on notebooks it could happen that the system is suspending and thus corrupting the backup. Disabling the power management while doing a backup could prevent the system from going to suspend. 

Also a warning before starting a backup in battery mode would be great. Requiring a full battery or refusing backups on battery at all could also be an option.

**Comment by spersson** [comment]
Thank you for the ideas! I was thinking about these things early on in development of Kup... but I guess I later forgot about it. So yes, I agree that stopping the system from shutting down or hibernating/sleeping would be a good thing. Especially since I have recently included the ability to stop rsync backup jobs. For bup there's still only pause function.

For backups taken while on battery I can think of two options that both seem OK to me. In both options the behavior when on AC is unchanged from how Kup behaves today.
1.  When on battery the only change is that even if the user has configured the backup plan to not ask before starting backup job, the question will be asked anyway... since they now maybe don't want this very automatic backup to start.
2. Take it one step further, when user is on battery don't do any automatic backup and don't even ask if user wants to do backup. Do nothing. User can still manually start a new backup job if they want it.

Any opinion on why one of these options would be the better one? Any other options?

**Comment by spersson** [comment]
Regarding the prevention of sleep/suspend, that turned out to only work for automatic sleep (user inactive for more than X minutes), not for when user clicks "suspend" button. Which is probably a good thing.  Could have been nice if Plasma detected that sleep suppression is active when manually suspending, and still not stop the user but at least show a warning then. 

Regarding saving of new backups while on battery... I decided to do option 1, thinking that most users are probably aware if they are on battery or not. So I just make sure to give a choice of not saving a new backup. The popup notification/question can just be ignored and no saving of backups will happen.
