### ISSUE TITLE
Superuser access

### ISSUE THREAD

**Issue by rokups** [spersson/Kup#52]
I tried Kup yesterday and i noticed that there is no way to back up data that user normally does not have access to. Even if user is in sudoer's list there is no way to elevate access to access files readable only by root. Could we get this functionality?

**Comment by spersson** [comment]
It was requested previously. I went ahead and added it and released a new version. Some version later I removed it again after thinking some more about it. I had realized that my original plan of being able to use kup for system backup was not something I wanted to support. I was thinking that for many users it's not very interesting - can always download a new OS installer. And also, if you are gonna do a system backup so that you can quickly get the system up and running... then you probably want some restore program that can write boot sector of your HDD anyway. Some kind of rescue boot CD image thing.
Although I wouldn't expect kup users to backup anything outside of their home directory, it's still possible... because why not. But for superuser access, bup itself is not designed to be executed with root access by a non-privileged user... no guarantees there. I'm just saying that to point out that there is a cost and risk with adding this. Otherwise I could of course have added it because why not.
Thanks for taking the time to report! Don't be shy to open up issues if you think of something else that could be improved.
