### ISSUE TITLE
How to start a backup if no taskbar?

### ISSUE THREAD

**Issue by lcswillems** [spersson/Kup#57]
Thank you for this great backup tool! Simple and very convenient!
I use i3wm and the task bar (the bar at the bottom of the screen containing all the widgets) is not present. How could I start a backup?

**Comment by spersson** [comment]
Kup has since the start targeted the plasma desktop. I decided on that since I wanted something really good, not something mediocre that works for more people. I know earlier versions were used by people with gnome shell or unity, at that time Kup used a systray icon with simple popup menu to control it. I actually don't know if the notifications worked with those desktop environments. But nowadays Kup needs plasma shell to be useful.

Well.. actually it could be that it works to use it if you configure your backup plan to not ask before starting to save stuff. It can just do it's thing in the background, saving as soon as the backup interval has passed and backup destination is available. You can always check status of backup plan by running "kcmshell5 kup".

**Comment by lcswillems** [comment]
I understand your point. But, just adding a "Backup" button (disable if it is not time for the Backup) on each plan (in the "configure backup plans") will solve all the issues (with Gnome, Unity also). No need to do complicated things with the tray icons (that I understand may be painful to implement).

As I said, your tool is really simple and powerful (I used DejaDup Backup and your tool is as simple and more powerful), and you could help a lot of people by just adding a button on each plan to start a Backup following the plan.

Thank you for your help. Do you know if there is a command to start a backup from command line?
