### ISSUE TITLE
New synchronized backup first deletes the contents of the destination, which could be very destructive

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#74]
I created a new synchronized backup to an external hard drive with some stuff in it. I deleted the text in the "Folder on destination drive" and started the backup, which immediately caused the contents of the external hard drive to be removed prior to starting the new backup task. I was never warned that this combination of options was destructive and would cause the erasure of the existing contents of the disk.

**Comment by spersson** [comment]
Oh shit, not good. Do you have an opinion on the best solution? In some way I can see why you would want to do this empty path.. like if you use this external drive daily to access your files from different computers or such, could be nice to minimize number folders inside of folders nesting level. I had already done changes to kup for avoiding this when possible, instead of storing full file paths on the destination drive. But. Doing what you did will basically make it impossible to store anything that is not managed by Kup. Does anybody actually want this? Seems like a good way to shoot yourself in the foot. Even if you had an empty disk to start with, then sync using Kup, then add other files... next time you sync the other files will be deleted. Easy to forget, even if I would show a warning when you configure a Kup backup plan.
Perhaps best just to insist that the folder selection is not empty. How to do that... Easiest is just a warning message that it can't be empty (and changed logic in the backup plan executor to refuse to run a sync in case it is empty). Normally I don't want to disable the save button.. actually don't remember if that is even possible.
Also could modify the plan settings when user clicks save: if the field is empty then, set some default like ${HOST}-backup or such.

**Comment by Pointedstick** [comment]
Yeah, what might make sense here is to always add a prefix (`Backups`?) rather than dumping all the files into the path/disk specified. My intention was definitely not to have all the files dumped there with no prefix. To that effect, it might be nice if Kup actually showed the final path that it will back up to. If it had done that, I would have seen that it was going to put files in `/home/nate/ /run/media/` rather than `/home/nate/ /run/media/nate/` (as I was hoping, and which might have caused it to re-use the existing rsync-created backup`

**Comment by spersson** [comment]
I went for a different solution, always creating folders in the destination folder. I hope that significantly reduces the risk of deleting files that the user did not intend.

**Comment by Pointedstick** [comment]
:ok_hand: :+1:
