### ISSUE TITLE
New synchronized backup first deletes the contents of the destination, which could be wasteful

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#75]
I set up a new Synchronized backup to an external hard drive that already had a backup folder on it that was previously created with `rsync -av --delete /home/nate/ /run/media/nate/Backup/nate/`. Instead of re-using this existing data, Kup deleted the old backup and started creating a new one.

I know it's kind of a niche use case, but it would have been nice if it had noticed the presence of a prior backup and re-used it rather than deleting it and starting over from scratch, which took over an hour.

**Comment by spersson** [comment]
Thanks for yet another good report!
Kup doesn't perform anything like delete all contents on first run or such. It only runs the rsync command based on your selection of what to save. Assuiming you only selected your home folder to be saved by Kup I would have thought Kup would run a very similar rsync command to what you said. And in that case files should be reused. Did the files end up where you had them previously? Not some /nate/nate folder? Can you check the log file (open from systray applet) and compare the command that Kup runs?

**Comment by Pointedstick** [comment]
No, previously my backup disk had:
`/run/media/nate/Backup/nate/[contents of home folder]`
...Which I had created myself with rsync.

The backup that Kup created is:
`/run/media/nate/Backup/[contents of home folder]`

So immediately upon starting, it deleted the `nate` folder that was at the root level of the backup disk. If I try again and add "nate" to the "Folder on Destination Drive" text field, then it does the right thing and re-uses the existing backup, producing a backup that consists of `/run/media/nate/Backup/nate/[contents of home folder]`

**Comment by spersson** [comment]
So with the change to resolve #74 , kup will now do what you expected to happen. But of course, another user might expect something else. That is the root of this issue, I believe. But I am very unsure how to make a user interface that shows the user how the resulting folder structure will look. And if it is worth showing such a thing (worth it in terms of user interface complexity).
Another point is that you got bitten extra bad since your files got deleted. With the latest fix to kup, in the scenario that you misunderstood where files will end up, you could maybe notice that copying is taking longer than it should and cancel the operation. Since no files got deleted you can then adjust settings or move files/folders. Then run a backup save operation from kup again.
I think I will close this issue but feel free to reopen in case you have a concrete idea how to improve this.

**Comment by Pointedstick** [comment]
Definitely good enough for now, thanks!
