### ISSUE TITLE
Formally become a KDE project

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#76]
Kup uses KDE technologies and integrates really well with Plasma and System Settings. I think it would be helpful to become a KDE project, with hosting on https://kde.org. This would open it up to KDE's translation infrastructure, allow the release team to handle releases for you (but only if you want, obviously), give you access to the promo team's resources so they could make sure the release announcements always look great, and finally increase visibility to the universe of KDE contributors. I expect the combination of these would provide a big increase in contributions from others,making the project less dependent on you personally and more likely to live on forever.

While KDE currently uses Phabricator for patch review, if you don't like that you can actually use Gitlab instead (https://invent.kde.org), which is a lot like Github and we're going to be moving everything to in the coming months.

**Comment by spersson** [comment]
Yeah, I've been thinking of that every now and then over the years. I had my KDE contributor account long before I started Kup. Never got around to do anything about it. I guess mostly because it required effort which was not straight forward (who would I even talk to), and doubts if it really fits in. Like on https://community.kde.org/Incubator it mentions requirements for a healthy bus number and attending events. On the other hand, Kup could really benefit from other developers working on it. Since it "works for me" I have not had much motivation to work on it for the last 4-5 years. Just keeping it alive both for myself and because so many people seem to like using it.
The big risk I see here is going through the process of adding to KDE incubator only to get kicked out a year later because I still barely touch the thing, and nobody else came to help. Basically it would force me to not only fix bugs when needed, but to spend time adding features to it, just to prove that it is an active project. (Or you need to keep finding bugs for me hehehehe)

**Comment by spersson** [comment]
I just realized that what I said above was perhaps a bit arrogant... As if joining KDE would not bring more bug reports and keep me busy just maintaining kup. Anyway, the main thing here is just if I want to commit myself to doing more than the bare minimum of fixing serious bugs.
Thank you again for your bug reports, seeing this level of interest definitely gives me motivation to work on Kup. In the last few years I have mostly worked on creating a programming language, a side project which so far has gone nowhere. I could be tempted to put that to the side and return focus to Kup. I will think some more about it.

**Comment by Pointedstick** [comment]
Thanks for the background info. In practice I don't think there's really any burden to it being a KDE project. On the contrary, I see the opposite effect in practice: over time other community members will contribute development resources and you can actually step away from the project without fear that it will die. This is even more true if Kup gets shipped by default anywhere and its number of users rises greatly. This has happened with Dolphin, Gwenview, Okular, and Spectacle, just to name a few I'm personally familiar with. None of their original authors are much involved anymore; the apps are either community-maintained or have different maintainers. And they're all alive and well!

I would be happy to be your sponsor if you wanted to begin the incubation process. No pressure, of course. It's just an idea. :)

**Comment by Pointedstick** [comment]
BTW I just updated https://community.kde.org/Incubator, so it now has up-to-date information regarding how to begin this process.

**Comment by spersson** [comment]
KDE incubator process is under way, closing issue.
