### ISSUE TITLE
Feature request: Version backups

### ISSUE THREAD

**Issue by anarchotaoist** [spersson/Kup#96]
Hello,

I would love to use Kup in Kubuntu 20.04.
Bup however is no longer in the Ubuntu packaging making versioned backups no longer possible.
Is it possible to package it with Kup - in a Flatpak etc?
Thanks.

**Comment by spersson** [comment]
Hello!
Thanks for informing about the issue! I have been in contact with someone working on getting bup back into debian, that is the proper fix and I hope it can be worked out soon. But even then these distros release cycles will delay any fix reaching users. In the mean time.. what to do? Perhaps there's an ubuntu PPA that has bup in it? Otherwise install bup yourself from source ,it's very easy. I don't think flatpak/snap are possible solutions since they are useful for standalone applications but not for something that integrates into the system (at least as far as I know).

**Comment by anarchotaoist** [comment]
Hello, 
thanks for the follow up with debian!
Unfortunately I could not understand the compile. The "Average Llinux User' who did a Youtube video on Kup tried to compile Bup in Kubuntu 20.04 also but could not do so. Other dependencies were also missing.
Thanks.

**Comment by spersson** [comment]
If I understand things correctly the main thing is that python 2 has been removed from debian and bup still depends on it. Bup developers are busy porting their code to python 3 but no software release yet.
