### ISSUE TITLE
Bup no more included in Ubuntu

### ISSUE THREAD

**Issue by carlonluca** [spersson/Kup#98]
It seems that bup is not more included in Ubuntu. I tried to report to bup list but there does not seem to be much interest in taking care of the problem.
Proposal: maybe bup could be embedded somehow into Kup?

**Comment by spersson** [comment]
The situation is not good, I see that. Many users are complaining. The problem is python 2. Bup project is working on the port to python 3. Embedding python 2 and bup into kup is possibly a solution if somebody is desperate enough to work on it. But that is most definitely a packaging issue, not upstream kup.

**Comment by carlonluca** [comment]
Yes, I understand this is not a bug in Kup, but the fact that Kup is not supporting a considerable amount of features, it is not even letting users access their own backups made with Kup and probably not going to work for the years to come on a LTS release, seems a relevant problem from a Kup point of view.
