### ISSUE TITLE
Please make a Flatpak version

### ISSUE THREAD

**Issue by carobinario** [spersson/Kup#99]
Hi,
I switched from Kubuntu 19.10 to Fedora 32. Unfortunately Kup isn't available in any repository and the one you suggest (http://download.opensuse.org/repositories/home:/simper:/kup/) only support Fedora up to 30 version or Fedora Rawhide. So, at this time I have backups on my HD but I can't update them.

I've also read kup has problems with Kubuntu 20.04.

Why don't you release Kup as a flatpak?

Thanks

**Comment by spersson** [comment]
I was under the impression that flatpak is a format for applications, not system services. Kup needs deep integration into the system. If you think otherwise you are welcome to make such a package! I don't know if fedora has packages for python 2 anymore, so maybe they also have stopped supporting bup. The bup project are well aware and are working on it.

**Comment by carobinario** [comment]
Hi,
sorry I'm not a coder or a software developer, so I can't make a Flatpak or any other package.

I opened this issue because I have a big backup made with kup under Kubuntu 19.10 and I can't use it in Kubuntu 20.04 or in Fedora 32. It's a big problem, you should keep this issue open instead of closing it. Thank.

**Comment by spersson** [comment]
I see that it's a problem, many users have been reporting this issue already. But it remains a packaging issue on certain distros only. I usually don't like to just say that it's somebody elses problem but in this case I don't see what I could do to help.
For accessing backups that should work fine with kup's kioslave. It will just be the Restore button in kup file digger that will not work. You can still open folders and copy out files from there.
